### ISSUE TITLE
Not saving input

### ISSUE THREAD

**Issue by ghost** [Ge0/chattymarkov#3]
I combinded chattymarkov with my discord bot, so that it stores every sent message in a .JSON-file. The problem is, that it only makes changes in that file, when I stop the bot. 
When I use the command "free -m", I can see, that it is using my RAM. Is there a way to store the data into the .JSON-file while the bot is running?

**Comment by Ge0** [comment]
Hi,

Could you provide me with some of your snippets so I can figure it out? I am not sure what you are talking about.

**Comment by Ge0** [comment]
Actually I think that I see what you mean.

The `JSONFileDatabase` class behaves in that the file is saved only when the program exits.

I designed it this way in order to avoid large I/O, because JSON isn’t really appropriated for such a use case.

Have you tried to use redis with your bot?

**Comment by ghost** [comment]
I have never heard of redis before, I am going to try it out!

**Comment by ghost** [comment]
ok, it is working with redis! Pretty easy, thanks for the fast reply!
